trigger:
- main  # Define the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Choose the desired agent image

steps:
- script: |
    echo "Hello, Azure DevOps!"  # Add your build commands here
    # Example commands:
    # npm install
    # npm run build
    # dotnet build

  displayName: 'Run Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Define the path to artifacts
    artifactName: 'build-output'  # Name of the artifact
